# Generated by Django 5.1.1 on 2024-10-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=20)),
                ('GST_ID', models.CharField(max_length=20)),
            ],
        ),
    ]
